[package]
name = "razorback"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
indoc = "2.0.2"
pest = "2.7.0"
pest_derive = "2.7.0"
rand = "0.8.5"
razorback_derive = { path = "../razorback_derive" }
thiserror = "1.0.43"
